### ISSUE TITLE
Question about GPU processing

### ISSUE THREAD

**Issue by aweaver1fandm** [thepetabyteproject/your#111]
**Describe the bug**
First I want to be clear that this isn't necessarily a bug.  I just need some guidance if that's possible.  I'm trying to run your_candmaker.py on our cluster using a GPU.  Our cluster has one node with 4 GPUs in it.  I have setup your in it's own Conda environment with nothing else in that environment.  I can submit a single job through SLURM and your_candmaker.py runs fine.  However, when I run multiple jobs I have issues -->

```batch
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/apps/miniconda3/envs/your/bin/your_candmaker.py", line 139, in cand2h5
    cand = gpu_dedisp_and_dmt_crop(cand, device=gpu_id)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/your/utils/gpu.py", line 157, in gpu_dedisp_and_dmt_crop
    cuda.select_device(device)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/numba/cuda/api.py", line 429, in select_device
    context = devices.get_context(device_id)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 144, in get_or_create_context
    return self._activate_context_for(devnum)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 176, in _activate_context_for
    gpu = self.gpus[devnum]
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
    return self.lst[devnum]
IndexError: list index out of range
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/apps/miniconda3/envs/your/bin/your_candmaker.py", line 349, in <module>
    pool.map(cand2h5, process_list, chunksize=1)
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/apps/miniconda3/envs/your/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
```

Based on some testing it seems like an issue with the GPU ID.  If the job gets submitted and tries to run on GPU 0, it seems to run okay.  If instead it gets assigned to GPU , for example, then we seem to get the above error.  If I go to our GPU node, activate the your CONDA environment and then directly in python do:

```bash
from numba import cuda
>>> cuda.select_device(1)
<weakproxy at 0x14c8091cd2b0 to Device at 0x14c8091b6620>
>>> cuda.detect()
Found 4 CUDA devices
id 0    b'Tesla V100-PCIE-32GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 61
                                    UUID: GPU-889b9a1a-9c37-818f-9443-27b6dd4506b6
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
id 1    b'Tesla V100-PCIE-32GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 62
                                    UUID: GPU-35e315e0-ddca-4313-dd2f-20b21a4ccb73
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
id 2    b'Tesla V100-PCIE-32GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 96
                                    UUID: GPU-27b705da-8199-c7b7-eedb-0ec2cdac3809
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
id 3    b'Tesla V100-PCIE-32GB'                              [SUPPORTED]
                      Compute Capability: 7.0
                           PCI Device ID: 0
                              PCI Bus ID: 97
                                    UUID: GPU-413441ca-6f4c-e73f-1b89-45866eee5851
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 2
Summary:
	4/4 devices are supported
True
```

I don't get any errors about list index out of range or anything.  

I'm just wondering if anyone else has tried running multiple instances of your to different GPUs and if you have it working and what we might be missing.  If not then please feel free to close this issue.

Thank you for your help

**Comment by aweaver1fandm** [comment]
I have done further testing and definitely narrowed it down to a problem with SLURM itself.
