### ISSUE TITLE
Hello, when I run the tutorial of reading files, your_object = your.Your(fil_file), I have the problem

### ISSUE THREAD

**Issue by mabaisen** [thepetabyteproject/your#115]
Traceback (most recent call last):
  File "D:/Desktop/mycode/fetch-tf2/creat_candidates1.py", line 9, in <module>
    your_object = your.your.Your(fil_file)
  File "D:\Anaconda\envs\fetch\lib\site-packages\your\your.py", line 72, in __init__
    self.formatclass.__init__(self, self.your_file)
  File "D:\Anaconda\envs\fetch\lib\site-packages\your\formats\pysigproc.py", line 87, in __init__
    self.fp.fileno(), 0, mmap.MAP_PRIVATE, mmap.PROT_READ
AttributeError: module 'mmap' has no attribute 'MAP_PRIVATE'

I don't know how to fix it. Could you please help me find what's wrong with it.

**Comment by devanshkv** [comment]
It's probably a Windows based issue. Please switch to Linux.

**Comment by mabaisen** [comment]
> It's probably a Windows based issue. Please switch to Linux.
Thank you， Linux don‘t have this problem.
