### ISSUE TITLE
Writing fits files from 4 pol psrfits 

### ISSUE THREAD

**Issue by KshitijAggarwal** [thepetabyteproject/your#67]
**Describe the bug**
Writer doesn't correctly write data from 4 pol fits files.

**To Reproduce**
```
>> your_writer.py -f 4_pol_fits_file -t fits -nstart 0 -nsamp 5000 -o ./ -name test
>> your_header.py -f test.fits
``` 
This will show that the output file has only 1 pol, but its size would be 4 times larger.

```
>> your_viewer.py -f test.fits
.
.
.
Traceback (most recent call last):
  File "/home/kshitij/anaconda3/envs/grbfrb/bin/your_viewer.py", line 4, in <module>
    __import__('pkg_resources').run_script('your==0.6.3', 'your_viewer.py')
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/EGG-INFO/scripts/your_viewer.py", line 375, in <module>
    values.files, values.start, values.gulp, values.chan_std
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/EGG-INFO/scripts/your_viewer.py", line 139, in load_file
    self.read_data()
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/EGG-INFO/scripts/your_viewer.py", line 270, in read_data
    self.data = self.your_obj.get_data(self.start_samp, self.gulp_size).T
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/your/your.py", line 240, in get_data
    data = self.formatclass.get_data(self, nstart, nsamp, pol=pol)[:, 0, :]
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/your/formats/psrfits.py", line 392, in get_data
    data.append(self.read_subint(fsub, pol=pol))
  File "/home/kshitij/anaconda3/envs/grbfrb/lib/python3.6/site-packages/your-0.6.3-py3.6.egg/your/formats/psrfits.py", line 267, in read_subint
    data = data.reshape((self.nsamp_per_subint, self.nchan)).astype(np.float32)
ValueError: cannot reshape array of size 81920000 into shape (5000,4096)
```

This is because it actually wrote 4 pol data to the fits file, but the header info in the fits file is incorrect.

**Comment by KshitijAggarwal** [comment]
Fixed with version 0.6.5 6f576da947a540f56ae5c37543b82830f99741b4
